# Copyright (C) 2023 The Android Open Source Project
# Copyright (C) 2025 The TWRP Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
DEVICE_PATH := device/8849/TANK3

# Hack depends - For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# Build hacks
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_PREBUILT_ELF_FILES := true
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a55

# Assert
TARGET_OTA_ASSERT_DEVICE := TANK3,TANK 3

# Hardware - for MTK Chipsets only
BOARD_USES_MTK_HARDWARE := true

# Platform
PRODUCT_PLATFORM := mt6895
TARGET_BOARD_PLATFORM := $(PRODUCT_PLATFORM)

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := G91BoardV1
TARGET_NO_BOOTLOADER := true
TARGET_USES_UEFI := true

# Prebuilt
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
TARGET_RECOVERY_DEVICE_DIRS += $(DEVICE_PATH)
TARGET_RECOVERY_DEVICE_DIRS += $(DEVICE_PATH)

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_SUPER_PARTITION_SIZE := 9663676416

# Dynamic Partition
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_SIZE := $(shell expr $(BOARD_SUPER_PARTITION_SIZE) - 4194304 )
BOARD_MAIN_PARTITION_LIST := \
    system \
    odm_dlkm \
    product \
    vendor_dlkm \
    system_ext \
    vendor

#    system_dlkm \

# File System
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

BOARD_USES_VENDOR_DLKMIMAGE := true

# Workaround for error copying vendor files to recovery ramdisk
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_SYSTEM_DLKM := system_dlkm
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext

# Recovery
TARGET_NO_RECOVERY := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
#TARGET_RECOVERY_PIXEL_FORMAT := BGRA_8888
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab

# Properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

# Image settings
TARGET_NO_KERNEL := true
BOARD_RAMDISK_USE_LZ4 := true
TARGET_KERNEL_ARCH := $(TARGET_ARCH)
TARGET_KERNEL_HEADER_ARCH := $(TARGET_ARCH)
BOARD_PAGE_SIZE := 4096
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x3fff8000
BOARD_RAMDISK_OFFSET := 0x26f08000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_TAGS_OFFSET := 0x07c88000
BOARD_DTB_SIZE := $(stat -L -c %s $(TARGET_PREBUILT_DTB) )
BOARD_DTB_OFFSET := 0x07c88000
BOARD_HEADER_SIZE := 2128

# Vendor CMD
BOARD_VENDOR_CMDLINE := bootopt=64S3,32N2,64N2

# MkBootImage Args
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_PAGE_SIZE) --board ""
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
BOARD_MKBOOTIMG_ARGS += --vendor_cmdline $(BOARD_VENDOR_CMDLINE)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_TAGS_OFFSET)

# Vendor_boot recovery ramdisk
BOARD_USES_RECOVERY_AS_BOOT :=
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT :=
BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE :=
BOARD_MOVE_GSI_AVB_KEYS_TO_VENDOR_BOOT :=

BOARD_VENDOR_RAMDISK_FRAGMENTS := recovery
BOARD_VENDOR_RAMDISK_FRAGMENT.recovery.MKBOOTIMG_ARGS := --ramdisk_type RECOVERY

# Android Verified Boot
BOARD_AVB_ENABLE := true

# TWRP Configuration
TW_DEFAULT_LANGUAGE := ru
TW_EXTRA_LANGUAGES := false
TW_USE_TOOLBOX := true
TARGET_USES_MKE2FS := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_NO_FASTBOOT_BOOT := true
TW_INCLUDE_REPACKTOOLS := true
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true

# TWRP Modules - Tools
# Includes
TW_INCLUDE_LPDUMP := true
TW_INCLUDE_LPTOOLS := true
TW_INCLUDE_LIBRESETPROP := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_FUSE_EXFAT := true
# Excludes
TW_EXCLUDE_APEX := true
TW_EXCLUDE_TWRPAPP := true
#TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_PYTHON := true
# Fastbootd
#TW_INCLUDE_FASTBOOTD := true

# TWRP Display
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 130
#TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone29/temp
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_INPUT_BLACKLIST := "hbtp_vm"

# Resolution
TW_THEME := portrait_hdpi
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2460

# Statusbar icons flags 1080 x 2460
TW_STATUS_ICONS_ALIGN := center
#TW_CUSTOM_CPU_POS := 50
TW_CUSTOM_CLOCK_POS := 610
#TW_CUSTOM_BATTERY_POS := 800

# Screen density
TARGET_SCREEN_DENSITY := 480

TW_FRAMERATE := 60

# TWRP Crypto
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
BOARD_USES_METADATA_PARTITION := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_USE_FSCRYPT_POLICY := 2
TW_FORCE_KEYMASTER_VER := true

# Hack to get keymaster to recognize the key files
PLATFORM_VERSION := 14
PLATFORM_VERSION_LAST_STABLE := $(PLATFORM_VERSION)
PLATFORM_SECURITY_PATCH := 2024-03-05
BOOT_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)
VENDOR_SECURITY_PATCH := 2024-03-05
#ro.build.version.security_patch=2024-03-05
#ro.vendor.build.security_patch=2024-03-05

# Vendor Modules
TW_USES_VENDOR_LIBS := true
TW_LOAD_VENDOR_MODULES := true
TW_LOAD_VENDOR_BOOT_MODULES := true
#TW_LOAD_VENDOR_MODULES_EXCLUDE_GKI := true

# TWRP vibro
TW_NO_HAPTICS := true

# TWRP Backup options
TW_BACKUP_EXCLUSIONS := /data/fonts/files

# TWRP Debug-tools
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true

# TWRP Battery
TW_USE_LEGACY_BATTERY_SERVICES := true

# Maintainer/Version
TW_DEVICE_VERSION := 8849 TANK 3_20240422 - lopestom

# PBRP (PitchBlack recovery)
MAINTAINER := lopestom
PB_TORCH_PATH := "/sys/class/flashlight_core/flashlight"
PB_TORCH_MAX_BRIGHTNESS := 1

# OrangeFox
FOX_AB_DEVICE := 1
OF_DEVICE_WITHOUT_PERSIST := 1
OF_DISABLE_MIUI_OTA_BY_DEFAULT := 1
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
FOX_NO_SAMSUNG_SPECIAL := 1
OF_DEFAULT_KEYMASTER_VERSION := 4.1
OF_USE_LZ4_COMPRESSION := 1
FOX_VERSION := $(PRODUCT_DEVICE) by lopestom
OF_MAINTAINER := lopestom
OF_SCREEN_H := 1520
OF_STATUS_H := 72
OF_STATUS_INDENT_LEFT := 20
OF_STATUS_INDENT_RIGHT := 20
OF_CLOCK_POS := 0
OF_ENABLE_LPTOOLS := 1
OF_NO_ADDITIONAL_MIUI_PROPS_CHECK := 1
FOX_VENDOR_BOOT_RECOVERY := 1
OF_DISPLAY_FORMAT_FILESYSTEMS_DEBUG_INFO := 1
OF_USE_LEGACY_BATTERY_SERVICES := 1
FOX_USE_UPDATED_MAGISKBOOT := 1
